app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

if(request()->input('debug', false)){
	\Event::listen('Illuminate\Database\Events\QueryExecuted', function ($query) {
	    var_dump($query->sql, $query->bindings, $query->time);
	});
}

$s = 'social.';
Route::get('/social/redirect/{provider}',   ['as' => $s . 'redirect',   'uses' => 'Auth\AuthController@getSocialRedirect']);
Route::get('/social/handle/{provider}',     ['as' => $s . 'handle',     'uses' => 'Auth\AuthController@getSocialHandle']);


Route::get('/', function () {
	SEOMeta::setTitle('Bandingkan Sebelum Belanja');
    return view('welcome');
});

Route::get('jump', ['as' => 'product.redirect', 'uses' => 'ProductController@redirect']);

// sitemap routes
Route::get('products', ['as' => 'product.index', 'uses' => 'ProductController@index']);
Route::post('products/{id}/like', ['as' => 'product.like', 'uses' => 'ProductController@like']);
Route::post('products/{id}/unlike', ['as' => 'product.unlike', 'uses' => 'ProductController@unlike']);
Route::get('sitemap.xml', ['as' => 'sitemap.index', 'uses' => 'SitemapController@index']);
Route::get('sitemap-general.xml', ['as' => 'sitemap.index', 'uses' => 'SitemapController@general']);
Route::get('sitemap-product.xml', ['as' => 'sitemap.product', 'uses' => 'SitemapController@product']);


Route::get('sites/{slug}', ['as' => 'marketplace.show', 'uses' => 'MarketplaceController@show']);
Route::get('/sites/{marketplace}/{hierarchy}', ['as' => 'category.show', 'uses' => 'CategoryController@show'])
->where('hierarchy', '(.*)?');


Route::auth();

Route::get('/dashboard', 'HomeController@index');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Sofa\Eloquence\Eloquence;
use Jedrzej\Pimpable\PimpableTrait;
use Watson\Rememberable\Rememberable;
use Phumbor;
use Cache;
use Conner\Likeable\LikeableTrait;

class Product extends Model
{
    use PimpableTrait;
    use Rememberable;
    use LikeableTrait;

    protected $searchableColumns = [
        'name' => 100, 
        'description' => 10,
        'categories.name' => 5,
        'marketplace.name' => 5
    ];

    public $searchable = ['*'];
    public $sortable = ['*'];

    public $notSearchable = ['view_as', 'query', 'sort', 'page', 'debug'];
    
    protected $fillable = ['loc', 'lastmod'];

    public static function cacheable()
    {
        return config('site.product.relations.cacheable');
    }

    public function categories()
    {
        return $this->belongsToMany('App\Category');
    }

    public function getImageAttribute($value)
    {
        $value = str_replace('https://', '', $value);
        $value = str_replace('http://', '', $value);

        return Phumbor::url($value);
    }

    public function getUrlAttribute()
    {
        return base64url_encode($this->loc);
    }

    public function marketplace()
    {
        return $this->belongsTo('App\Marketplace');
    }

    public function related($limit = 10)
    {
        // search match case first
        $products = $this::search($this->name)->simplePaginate($limit);

        return $products;
    }

    public static function search($q, $filters = [], $sort = [])
    {
        // cache for one month
        $products =  self::remember(44640)->with(self::cacheable());
        
        if(!empty($q)){

            
            $products = $products->whereRaw('MATCH (name,description) AGAINST(?)', [$q]);
        }

        if(!empty($filters)){
            if(is_null($products)){
                $products = self::filtered($filters);
            }
            else{
                $products = $products->filtered($filters);
            }
        }
        if(!empty($sort)){
            if(is_null($products)){
                $products = self::sorted($sort);
            }
            else{
                $query = $products;
                $subquery = $query->getQuery();
                $subquery->orders = [];
                $query->setQuery($subquery);

                $products = $products->sorted($sort);
            }
        }

        return $products;
    }

    public static function total($products)
    {
        $query = $products->toSql() . '|||' . implode('||', $products->getBindings());
        $cacheKey = md5($query);

        $product_count = Cache::remember($cacheKey, 10080, function() use ($products){
            $product_count = 0;
            
            if($products->select('*')->skip(100)->take(1)->first()){
                return 100;
            }

            if($products->select('*')->skip(10)->take(1)->first()){
                return 10;
            }

            if($products->select('*')->first()){
                return 1;
            }

            return 0;
        });

        return $product_count;    
    }

    public static function getLikes($user_id) {
        return (new static)
            ->join('likeable_likes', 'products.id', '=', 'likeable_likes.likable_id')
            ->select('products.*')
            ->where('likeable_likes.user_id', '=', $user_id)
            ->orderBy('likeable_likes.created_at', 'DESC');
    }

}

resources/views/widgets/banner_cards.blade.php
<div class="row" style="margin-top:20px;">
    <div class="col-md-5">
        <a href="{{ route('product.index', ['categories:slug' => 'handphone', 'sort' => 'price,desc']) }}" class="thumbnail"><img class="img-responsive" src="{{ url('images/banners/rsz_sales_hp_idaman_375x350-01.jpg') }}" alt=""></a>
    </div>
    <div class="col-md-5">
        <div class="row">
            <div class="col-md-12">
                <a href="{{ route('product.index', ['query' => 'korea', 'categories:slug' => '%fashion%']) }}" class="thumbnail"><img class="img-responsive" src="{{ url('images/banners/rsz_sales_tampil_gaya_ala_korea_d45__375x170-07.jpg') }}" alt=""></a>
            </div>
            <div class="col-md-6">
                <a href="{{ route('product.index', ['query' => 'kesehatan pria']) }}" class="thumbnail"><img class="img-responsive" src="{{ url('images/banners/rsz_sales_finalharga_mulai_180x170-11.jpg') }}" alt=""></a>
            </div>
            <div class="col-md-6">
                <a href="{{ route('product.index', ['categories:slug' => '%mainan%']) }}" class="thumbnail"><img class="img-responsive" src="{{ url('images/banners/%28SALES%29-%28BANNER-PRIA%29-Aneka-Mainan-Harga-Mulai-45-Ribuan-180x170.jpg') }}" alt=""></a>
            </div>
        </div>
    </div>
    <div class="col-md-2">
        <a href="{{ route('product.index', ['categories:slug' => '%hadiah%']) }}" class="thumbnail"><img class="img-responsive" src="{{ url('images/banners/SALES_BAJU_ANAK_180x350_%281%29.jpg') }}" alt=""></a>
    </div>
</div>

resources/views/widgets/category_chooser.blade.php
<div class="list-group">
	<div href="#" class="list-group-item active">
    	<span class="panel-title">
			<i class="glyphicon glyphicon-tags"></i> Pilih Kategori
		</span>
  	</div>
	@foreach($categories as $category)
	<a href="{{ build_filter(['categories:slug' => $category->slug]) }}" class="list-group-item">
		<span class="badge">
			@if($ratio <= 1)
	    	{{ rp_terbilang($category->total) }}
	    	@else
	    	{{ rp_terbilang($category->total*$ratio) }}
	    	@endif
		</span>
    {{ $category->name }}
    </a>    
    @endforeach
</div>

resources/views/widgets/category_filter.blade.php
<h4>Kategori</h4>
@if(isset($config['category']->parent))
    <ul class="list-group">
        <li class="list-group-item"><a href="{{ build_category_parent_url() }}"><i class="fa fa-chevron-left"></i> {{ $config['category']->parent->name }}</a></li>
    </ul>
@else
	@if(isset($config['category']))
    <ul class="list-group">
        <li class="list-group-item"><a href="{{ route('marketplace.show', ['slug' => $config['marketplace']->slug]) }}"><i class="fa fa-chevron-left"></i> {{ $config['marketplace']->name }}</a></li>
    </ul>   
    @endif
@endif
@if(!is_null($config['category']))
<ul class="list-group">
	<li class="list-group-item active"><i class="fa fa-chevron-down"></i> {{ $config['category']->name }}</li>

    @foreach($config['category']->children()->remember(10080)->get() as $category)
    <li class="list-group-item">
        <a href="{{ build_category_url($category->slug) }}">{{ $category->name }}</a>
    </li>
    @endforeach
</ul>
@else
	<ul class="list-group">
    @foreach($categories as $category)
        <li class="list-group-item">
            <a href="{{ route('category.show', ['marketplace' => $config['marketplace']->slug, 'hierarchy' => $category->slug]) }}">{{ $category->name }}</a>
        </li>
    @endforeach
</ul>
@endif

resources/views/widgets/intro.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="text-center alert alert-info">
            <h1>Bandingkan Sebelum Belanja</h1>
            <p style="font-size: 1.3em;">
                {{ config('site.name') }} Mengindex <strong style="color: #b30143;">{{ $product_count }}</strong> produk dari {{ App\Marketplace::remember(5)->count('id') }}  marketplace di Indonesia

            </p>
            <div class="share-icons"></div>
        </div>
    </div>
</div>

resources/views/widgets/like_button.blade.php
@if(Auth::guest())
    <a rel="nofollow" href="#login-overlay" class="btn btn-default btn-small" data-toggle="modal" data-target="#login-overlay"><i class="fa fa-heart-o" aria-hidden="true"></i>&nbsp;{{ config('site.like.label') }}</a>

@else

    @if($product->liked())
        <a rel="nofollow" href="{{ route('product.unlike', ['id' => $product->id ]) }}" data-disable data-method="post" data-remote="true" class="btn btn-success btn-small btn-like"><i class="fa fa-bookmark" aria-hidden="true"></i> {{ config('site.like.label') }}
            <span class="like-count badge">
            @if($product->likeCounter)
            {{ $product->likeCounter->count }}
            @else
            0
            @endif
            </span>
        </a>
    @else
        <a rel="nofollow" href="{{ route('product.like', ['id' => $product->id ]) }}" data-disable data-method="post" data-remote="true" class="btn btn-default btn-small btn-like"><i class="fa fa-bookmark" aria-hidden="true"></i> {{ config('site.like.label') }}
            <span class="like-count badge">
                @if($product->likeCounter)
                {{ $product->likeCounter->count }}
                @else
                0
                @endif
            </span>
        </a>
    @endif

@endif

resources/views/widgets/location_filter.blade.php
<div class="list-group">
	<div href="#" class="list-group-item active">
    	<span class="panel-title">
			<i class="glyphicon glyphicon-map-marker"></i> Pilih Lokasi
		</span>
  	</div>
	@foreach($locations as $location => $count)
    <a href="{{ build_filter(['location' => strtolower($location)]) }}" class="list-group-item"><span class="badge">
    	@if($ratio <= 1)
    	{{ rp_terbilang($count) }}
    	@else
    	{{ rp_terbilang($count*$ratio) }}
    	@endif
    </span>
    {{ $location }}</a>
    @endforeach
</div>

resources/views/widgets/marketplace_filter.blade.php
<div class="list-group">
	<div href="#" class="list-group-item active">
    	<span class="panel-title">
			<i class="glyphicon glyphicon-shopping-cart"></i> Pilih Marketplace
		</span>
  	</div>
	@foreach($marketplaces as $marketplace)
    <a href="{{ build_filter(['marketplace:slug' => $marketplace->slug]) }}" class="list-group-item">
    <span class="badge">
    	@if($ratio <= 1)
    	{{ rp_terbilang($marketplace->total) }}
    	@else
    	{{ rp_terbilang($marketplace->total*$ratio) }}
    	@endif
    </span>
    {{ $marketplace->name }}</a>
    @endforeach
</div>

resources/views/widgets/marketplaces.blade.php
<div class="row" style="margin-top:20px;">

    @foreach(App\Marketplace::remember(5)->get() as $marketplace)
    <div class="col-md-2">
        <a href="{{ route('marketplace.show', [$marketplace->slug]) }}">
            <img class="img-responsive" src="{{ $marketplace->logo }}" alt="{{ $marketplace->name }}" />
        </a>
    </div>
    @endforeach

    @foreach(getLogos() as $logo)
    <div class="col-md-2">
        <img class="img-responsive desaturate" src="{{ url($logo) }}">
    </div>
    @endforeach
</div>

resources/views/widgets/price_chooser.blade.php
<div class="list-group">
	<div href="#" class="list-group-item active">
    	<span class="panel-title">
			<i class="fa fa-dollar"></i> Pilih Harga
		</span>
  	</div>
	@foreach($prices as $price)
    <a href="{{ build_filter(['price[min]' => $price->min, 'price[max]' => $price->max]) }}" class="list-group-item">
    <span class="badge">
    	@if($ratio <= 1)
    	{{ rp_terbilang($price->total) }}
    	@else
    	{{ rp_terbilang($price->total*$ratio) }}
    	@endif
    </span>
    {{ $price->round_price }}</a>
    @endforeach
</div>

resources/views/widgets/product.blade.php
<div class="panel panel-default">
    <div class="row">
        <div class="col-md-5">
            <a href="{{ $product->image }}"><img class="img-responsive" src="{{ $product->image }}" alt="{{ $product->name }}"></a>
        </div>
        <div class="col-md-7" style="padding: 0px 15px 0px 35px;">
            <h3 style="margin-top: 10px;">{{ $product->name }}</h3>
            <p>
                <i class="glyphicon glyphicon-tags"></i>&nbsp;
                @foreach($product->categories as $category)
                        
                    {{ $category->name }} 
                        
                    @if($product->categories->last() !== $category)
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    @endif
                @endforeach


            </p>
            <p>
	            <i class="glyphicon glyphicon-map-marker"></i> {{ $product->location }} &nbsp;
				<i class="glyphicon glyphicon-time"></i> {{ $product->created_at->diffForHumans() }}
            </p>
            <p class="money" style="margin-top:10px; font-size: 2em;">{{ format_money($product->price) }}</p>
			<table class="table table-detail">
		    	<thead>
		    		<tr>
		    			<th>Toko</th>
		    			<th>Situs</th>
		    		</tr>
		    	</thead>
		    	<tbody>
		    		<tr>
		    			<td width="25%">
		    				<a href="{{ route('marketplace.show', ['slug' => $product->marketplace->slug]) }}"><img class="img-responsive" src="{{ $product->marketplace->logo }}" alt="{{ $product->marketplace->name }}"></a>
		    			</td>
		 
		        		<td>
		        			<div class="btn-group btn-group-justified" role="group" aria-label="buka situs"> 
		        				@widget('likeButton', ['product' => $product])
		        				<a href="{{ route('product.redirect', ['u' => $product->url]) }}" rel="nofollow" target="_blank" class="btn btn-default btn-danger" title="{{ $product->name }}"><i class="fa fa-chevron-right"></i>  Buka Situs</a>
		        		</td>
		        	</tr>
		        </tbody>
		    </table>

        </div>
	</div>
</div>

<div class="panel panel-info" id="deskripsi">
	<div class="panel-heading"> 
        Deskripsi Barang
    </div>
	<div class="panel-body">
		<div class="row">
			<div class="col-md-12">
			    
			</div>
		</div>
		<div class="row">
			<div class="col-md-12" style="padding:10px 0px 10px 25px;max-height:150px;overflow-y:scroll;width:100%;">
				
		    	{!! strip_tags($product->description, '<p><br>') !!}
			</div>
		</div>
	</div>
</div>
<div class="row">
    <div class="col-md-12">
        <h2>Produk Sejenis <small>{{ $product->name }}</small></h2>
    </div>
</div>
<div class="infinite-scroll">
	@widget('products', [
		'products' => $related_products,
		'view_as' => 'list',
		'title' => ''
	])
</div>
<div class="text-center" id="pagination">
	{{ $related_products->links() }}
</div>

<div class="row" style="margin-bottom:20px;">
	<div class="col-md-6 col-md-offset-3">
			<a class="btn btn-success btn-block" href="{{ route('product.index', ['query' => strtolower($product->name)]) }}"><i class="fa fa-search"></i> Bandingkan Semua Produk Sejenis</a>

	</div>
</div>

resources/views/widgets/product_filter.blade.php
<div class="panel panel-default" style="background: #f7f7f7; border-top:3px solid #337ab7; padding: 10px;">
	<form action="{{ route('product.index') }}">
		@if(request()->has('query'))
			<input type="hidden" name="query" value="{{ request()->input('query') }}">
		@endif
		<!-- sort -->
		<div class="form-group">
			<label>Urutkan</label>
			<select name="sort" class="form-control">
				<option @if(request()->input('sort') === 'relevance') selected="selected" @endif value="relevance">Paling Relevan</option>
				<option @if(request()->input('sort') === 'price,asc') selected="selected" @endif value="price,asc">Harga Termurah</option>
				<option @if(request()->input('sort') === 'price,desc') selected="selected" @endif value="price,desc">Harga Termahal</option>
				<option @if(request()->input('sort') === 'updated_at,desc') selected="selected" @endif value="updated_at,desc">Update Terbaru</option>
				<option @if(request()->input('sort') === 'updated_at,asc') selected="selected" @endif value="updated_at,asc">Update Terlama</option>
			
			</select>
		</div>


		<!-- marketplace -->
		<div class="form-group">
			<label>Marketplace</label>
			<select name="marketplace:slug" class="form-control">
				<option @if(request()->input('marketplace:slug') === '%%') selected="selected" @endif value="%%">Semua Marketplace</option>
				@foreach($marketplaces as $marketplace)
				<option @if(request()->input('marketplace:slug') === $marketplace->slug) selected="selected" @endif value="{{ $marketplace->slug }}">{{ $marketplace->name }}</option>
				@endforeach
			</select>
		</div>

		<!-- harga -->
		<div class="form-group">
			<label>Harga</label>
			<div class="form-group">
				<div class="input-group">
				    <div class="input-group-addon">Rp</div>
				    <input name="price[min]" type="text" class="form-control" placeholder="Min" value="{{ (int)request()->input('price.min') ?: ''  }}">
			    </div>
			</div>
			<div class="form-group">
				<div class="input-group">
				    <div class="input-group-addon">Rp</div>
				    <input name="price[max]" type="text" class="form-control" placeholder="Max" value="{{ (int)request()->input('price.max') ?: ''  }}">
			    </div>
			</div>
		</div>

		<!-- kondisi -->
		<div class="form-group">
			<label>Kondisi</label>
			<select name="condition" class="form-control">
				<option value="%%">Baru &amp; Bekas</option>
				<option value="baru">Baru</option>
				<option value="bekas">Bekas</option>
			</select>
		</div>

		<!-- lokasi -->
		<div class="form-group">
			<label>Lokasi</label>
			<select name="location" class="form-control">
				<option @if(request()->input('location') === '%%') selected="selected" @endif value="%%">Semua Lokasi</option>
				@foreach($locations as $location)
				<option @if(request()->input('location') === $location) selected="selected" @endif value="{{ strtolower($location) }}">{{ ucwords($location) }}</option>
				@endforeach
			</select>
		</div>

		<button class="btn btn-primary btn-block" type="submit"><i class="fa fa-filter" aria-hidden="true"></i> Filter</button>

	</form>
	<a href="{{ url(request()->path()) }}" class="btn btn-block btn-link"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
 Reset Filter</a>
</div>

resources/views/widgets/time_chooser.blade.php
<div class="list-group">
	<div class="list-group-item active">
    	<span class="panel-title">
			<i class="glyphicon glyphicon-calendar"></i> Pilih Waktu
		</span>
  	</div>
	@foreach($times as $time)
    <a href="{{ build_filter(['created_at' => '(ge)' . $time->date_filter]) }}" class="list-group-item">
    <span class="badge">
    	@if($ratio <= 1)
    	{{ rp_terbilang($time->total) }}
    	@else
    	{{ rp_terbilang($time->total*$ratio) }}
    	@endif
    </span>
    {{ $time->date_interval }}</a>
    @endforeach
</div>